[0m12:32:19.416206 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107346400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11057fc70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11057f220>]}


============================== 12:32:19.436581 | 493f7083-037c-412b-881f-c3c839f4b810 ==============================
[0m12:32:19.436581 [info ] [MainThread]: Running with dbt=1.10.5
[0m12:32:19.448349 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/bi006217/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m12:32:19.514770 [info ] [MainThread]: Creating dbt configuration folder at /Users/bi006217/.dbt
[0m12:32:34.744508 [debug] [MainThread]: Starter project path: /Users/bi006217/Documents/study/dbt_bigquery/.venv/lib/python3.9/site-packages/dbt/include/starter_project
[0m12:32:34.761208 [info ] [MainThread]: 
Your new dbt project "dbt_core" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:32:34.761688 [info ] [MainThread]: Setting up your profile.
[0m12:34:52.207149 [info ] [MainThread]: Profile dbt_core written to /Users/bi006217/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m12:34:52.221805 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 152.91338, "process_in_blocks": "0", "process_kernel_time": 0.817472, "process_mem_max_rss": "324927488", "process_out_blocks": "0", "process_user_time": 3.384248}
[0m12:34:52.222662 [debug] [MainThread]: Command `dbt init` succeeded at 12:34:52.222491 after 152.91 seconds
[0m12:34:52.223520 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107346400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1105b4bb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1638d05e0>]}
[0m12:34:52.224172 [debug] [MainThread]: Flushing usage events
[0m12:34:53.474919 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:03:47.515393 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103222220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104294c70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104294220>]}


============================== 19:03:47.519847 | b60efc5f-7bb5-4062-9ccb-8df15911c492 ==============================
[0m19:03:47.519847 [info ] [MainThread]: Running with dbt=1.10.5
[0m19:03:47.520429 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/bi006217/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'invocation_command': 'dbt run', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:03:47.521072 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/bi006217/Documents/study/dbt_bigquery/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:03:47.524107 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.0862035, "process_in_blocks": "0", "process_kernel_time": 0.288833, "process_mem_max_rss": "97107968", "process_out_blocks": "0", "process_user_time": 1.273055}
[0m19:03:47.524625 [debug] [MainThread]: Command `dbt run` failed at 19:03:47.524528 after 0.09 seconds
[0m19:03:47.524993 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103222220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104294ee0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104294f70>]}
[0m19:03:47.525539 [debug] [MainThread]: Flushing usage events
[0m19:03:49.888063 [debug] [MainThread]: An error was encountered while trying to flush usage events
